#!/bin/bash
count=`ps aux | grep "cafe_grader" | grep "grader grading queue" | wc -l`
expected=`mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -h db -sN -D $MYSQL_DATABASE -e "SELECT value FROM grader_configurations WHERE \\\`key\\\` = 'system.default_grader_queue_amount';"`
if [ $count -lt $expected ]; then
  count=$(($count + 1))
  for i in $(seq $count $expected);
  do
    stty -tostop; (ruby /cafe_grader/judge/scripts/grader grading queue > /dev/null &)
  done
fi
count=`ps aux | grep "cafe_grader" | grep "grader grading test_request" | wc -l`
expected=`mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -h db -sN -D $MYSQL_DATABASE -e "SELECT value FROM grader_configurations WHERE \\\`key\\\` = 'system.default_grader_test_request_amount';"`
if [ $count -lt $expected ]; then
  count=$(($count + 1))
  for i in $(seq $count $expected);
  do
    stty -tostop; (ruby /cafe_grader/judge/scripts/grader grading test_request > /dev/null &)
  done
fi
